name: deploy 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up the build environment
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y build-essential

      # - name: Install dependencies
      #   run: npm install --force

      # - name: Build Docker image
      #   run: docker build -t my-app .

      - name: Deploy to server
        uses: actions/ssh-script@v6
        with:
          host: 150.95.25.8
          username: root
          password: obj,db99bd6]TTT
          script: |
            cd /project/Just4Demo
            docker-compose down
            docker-compose build app
            docker-compose up -d